Handle TransferToEthereum
anoma/namada pull request #1072
Opened 2023-01-23 17:29 UTC by yito88

- Add the inserted height to the Merkle tree of the bridge pool for the timeout checking
- Handle TransferToEthereum event
  - Delete the pending transfers contained in the event
  - Refund and delete for timed-out transfers

2023-01-24 09:31 UTC, sug0 reviewed
a few comments, but otherwise lgtm

2023-01-24 09:31 UTC, sug0 commented on ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
> +            ));
I think the only way we could have run into this code path is if a quorum of validators decided on an event that didn't happen (that is, effectively, we would have had a Byzantine quorum of validators at that point). to transfer to Ethereum, users need to provide a proof that they sent a transfer to the bridge pool, at which point their transfer would be registered in storage.

therefore, maybe it's wiser to panic here? or use `unreachable!()`? there's also `namada_core::hints::likely()`, for the optimistic if branch.

2023-01-25 09:46 UTC, batconjurer requested changes

2023-01-25 09:46 UTC, batconjurer commented on core/src/ledger/eth_bridge/storage/bridge_pool.rs
> +    pub fn insert_key(
nit: The rest of the trees follow a key-value order for the insert arguments.

2023-01-25 09:46 UTC, batconjurer commented on core/src/ledger/storage/merkle_tree.rs
>      fn update_tree(
Let s just the make the height the value of the tree.

2023-01-25 09:46 UTC, batconjurer commented on core/src/ledger/storage/traits.rs
> +
I think we should just tree the block height as the value type of the tree. Then we can use all the existing interfaces.

2023-01-26 09:27 UTC, batconjurer requested changes

2023-01-26 09:27 UTC, batconjurer commented on core/src/ledger/storage/merkle_tree.rs
> +    pub fn update(
can't we just pass the blockheight in as the value parameter here?

2023-01-26 09:37 UTC, sug0 approved these changes
lgtm, just a small suggestion

2023-01-26 09:37 UTC, sug0 commented on ethereum_bridge/src/protocol/transactions/ethereum_events/events.rs
> +            unreachable!()
nit: you can add the message in the comment to the panic itself
```suggestion
            unreachable!("The transfer should exist in the bridge pool");
```

2023-01-27 08:38 UTC, sug0 approved these changes

2023-01-27 11:52 UTC, batconjurer approved these changes

2023-01-27 12:30 UTC, batconjurer requested changes
I have thought of a mild security concern that should be addressed actually. WIll leave comments in the relevant places.

2023-01-27 12:32 UTC, batconjurer approved these changes
I have thought of a mild security concern that should be addressed actually. WIll leave comments in the relevant places.

2023-01-27 12:33 UTC, batconjurer commented
> I have thought of a mild security concern that should be addressed actually. WIll leave comments in the relevant places.

Actually, it's fine.

2023-01-27 12:35 UTC, merged