Start the Ethereum event oracle from the correct Ethereum block between node restarts
anoma/namada pull request #1101
Opened 2023-01-30 12:52 UTC by james-chf

Relates to https://github.com/anoma/namada/issues/1046

2023-02-09 11:49 UTC, james-chf commented
Needs an e2e test

2023-02-09 11:52 UTC, james-chf commented on core/src/types/ethereum.rs
> +    inner: Uint256,
This `Uint256` type is what we (and our web3 crate) are mostly using to represent Ethereum block heights, we need something Borsh-serializeable for storage though

2023-02-09 11:52 UTC, james-chf commented on core/src/ledger/storage/local_node.rs
> +pub struct EthereumOracleLastProcessedBlock;
There are other local node values we currently store in RocksDB (e.g. `tx_queue`)

2023-02-15 12:33 UTC, batconjurer commented on apps/src/lib/node/ledger/ethereum_node/oracle/last_processed_block.rs
> +//! Functionality to do with publishing which blocks we have processed.
This probably doesn't need to live in a separate file.

2023-02-16 09:51 UTC, sug0 requested changes

2023-02-16 09:51 UTC, sug0 commented on apps/src/lib/node/ledger/ethereum_node/oracle/mod.rs
> +pub mod last_processed_block {
nit: module docstrings need to be moved inside the module
```suggestion
pub mod last_processed_block {
    //! Functionality to do with publishing which blocks we have processed.
```

2023-02-16 09:51 UTC, sug0 commented on apps/src/lib/node/ledger/shell/mod.rs
> +            };
`self.storage.ethereum_height.cloned().unwrap_or_default()`?

2023-02-16 09:51 UTC, sug0 commented on core/src/types/ethereum.rs
> +use num256::Uint256;
couldn't we simply use the uin256 type from `ethabi`? `num256` could be purged from our deps

2023-02-16 09:51 UTC, sug0 commented on core/src/types/ethereum.rs
> +#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
```suggestion
#[derive(Default, Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
```

2023-02-16 09:56 UTC, sug0 commented
another thing, which I forgot to mention in the review: we now have `core/src/types/ethereum_structs.rs`. we could move this `BlockHeight` def there

2023-02-16 10:44 UTC, sug0 commented on core/src/types/ethereum.rs
> +use num256::Uint256;
ah, that's a shame

2023-02-16 11:02 UTC, sug0 approved these changes

2023-02-16 11:02 UTC, sug0 commented on core/src/types/ethereum_structs.rs
> +//! Ethereum bridge struct re-exports adn types to do with ethereum.
```suggestion
//! Ethereum bridge struct re-exports and types to do with ethereum.
```
just this type here. otherwise lgtm

2023-02-16 12:36 UTC, merged