Eth event timeout
anoma/namada pull request #1167
Opened 2023-02-20 13:28 UTC by yito88

2023-02-21 13:20 UTC, batconjurer reviewed
Just a variable name change. Otherwise looks good.

2023-02-21 13:48 UTC, sug0 requested changes
nits

2023-02-21 13:48 UTC, sug0 commented on ethereum_bridge/src/protocol/transactions/ethereum_events/mod.rs
> +    for keys in get_timeout_events(storage) {
nit: rename to `get_timed_out_eth_events()`?

2023-02-21 13:48 UTC, sug0 commented on ethereum_bridge/src/storage/vote_tallies.rs
> +    /// Get the `epoch` key - there should be a `Epoch` stored here.
```suggestion
    /// Get the `epoch` key - there should be an [`Epoch`] stored here.
```

2023-02-22 09:05 UTC, batconjurer approved these changes

2023-02-22 15:48 UTC, merged