Added erc20 token amount type
anoma/namada pull request #1233
Opened 2023-03-20 10:00 UTC by batconjurer

This PR closes #1085, #1089, and #1090.

A new type, `Erc20Amount` has been added for amounts of ERC20 tokens according to the [EIP-20 specification](https://eips.ethereum.org/EIPS/eip-20). Whitelisted ERC20 tokens must now keep a denomination in storage. These denominations must also be kept in sync with the oracle, which needs them for processing ethereum events.

2023-03-27 13:55 UTC, sug0 requested changes
might need another review pass, since token whitelists need some changes to allow transfers to ethereum, even if a whitelist update removes a token whose balance is still greater than 0 for some namada client

2023-03-27 13:55 UTC, sug0 commented on ethereum_bridge/src/storage/eth_bridge_queries.rs
> +                return Some(6);
nit: maybe implement a const fn `token::Amount::denomination() -> u8 { 6 }`?

2023-03-27 13:55 UTC, sug0 commented on shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
> +                                     be escrowed into the bridge pool: {:?}",
nit: assuming this implements `Error`, it's best to display the actual error string
```suggestion
                                     be escrowed into the bridge pool: {}",
```

2023-03-27 13:59 UTC, sug0 commented on apps/src/lib/cli.rs
> +            }
https://docs.rs/clap/latest/clap/error/struct.Error.html
maybe we could also use this API instead of panicking

2023-03-28 08:09 UTC, batconjurer commented
> might need another review pass, since token whitelists need some changes to allow transfers to ethereum, even if a whitelist update removes a token whose balance is still greater than 0 for some namada client

Yes, but that will be another PR.

2023-04-13 13:16 UTC, sug0 commented
This PR contains an implementation that closes https://github.com/anoma/namada/issues/1290

2023-07-15 13:42 UTC, sug0 commented
Superseded by https://github.com/anoma/namada/pull/1718 and https://github.com/anoma/namada/pull/1282

2023-07-15 13:42 UTC, closed without merging