Generic IO
anoma/namada pull request #1746
Opened 2023-07-21 22:27 UTC by batconjurer

This code replaces IO in sdk and client code with a trait that allows custom IO handling.

2023-07-24 14:13 UTC, tzemanovic commented on apps/src/lib/cli/wallet.rs
> +        IO::println(format!("Viewing key: {}", viewing_key));
let's use the macros in this file

2023-07-24 15:40 UTC, tzemanovic submitted a review, later dismissed

2023-07-25 07:27 UTC, tzemanovic submitted a review, later dismissed

2023-07-26 10:15 UTC, mateuszjasiuk approved these changes
Sorry for later review!
So I was able to implement the trait in browser.
In general all of this works great, the two things to comes to my mind though:
- Sometimes it is a bit annoying to pass generic IO as last type `namada::ledger::tx::build_transfer::<_, _, _, IO>`, as first three types can be inferred
- it would be nice to make prompt and read async. The reason is that when we use those functions in the extension background(service worker) we do not have access to prompt(or any other DOM related features). So to make it work we would have to do something like this: [stackblitz](https://stackblitz.com/edit/typescript-jdvple?file=index.ts). On the other hand though, at the moment we are not using prompts at all, so this might not be such a big issue.

2023-07-26 11:21 UTC, batconjurer commented
So I can change the order of the generic arguments, but it's a choice of `namada::ledger::tx::build_transfer::<_, _, _, IO>` vs `namada::ledger::tx::build_transfer::<IO _, _, _>`. I don't know if it's worth it for the same amount of typing in the end.

2023-07-26 11:27 UTC, batconjurer commented
However, I made the `read` and `prompt` methods async. That is easy.

2023-07-26 13:59 UTC, mateuszjasiuk commented
> So I can change the order of the generic arguments, but it's a choice of `namada::ledger::tx::build_transfer::<_, _, _, IO>` vs `namada::ledger::tx::build_transfer::<IO, _, _, _>`. I don't know if it's worth it for the same amount of typing in the end.

Ah my bad, I thought they can be skipped the same as in TS 😅 
Nvm then

2023-07-26 15:02 UTC, mateuszjasiuk submitted a review, later dismissed

2023-07-27 09:24 UTC, tzemanovic commented on shared/src/types/io.rs
>          read_aux(std::io::stdin().lock())
let's also switch these to use non-blocking io with `tokio::io::stdin`

2023-07-27 09:24 UTC, tzemanovic commented on shared/src/types/io.rs
>              std::io::stdin().lock(),
and here

2023-07-27 14:25 UTC, tzemanovic approved these changes

2023-07-28 09:21 UTC, mateuszjasiuk submitted a review, later dismissed

2023-08-14 09:16 UTC, sug0 requested changes
Hey, I noticed `apps/src/bin/namada-client/cli.rs` hasn't been deleted yet, despite the module not being referenced from any rust source file.

2023-08-16 07:34 UTC, sug0 submitted a review, later dismissed

2023-08-16 14:18 UTC, tzemanovic approved these changes

2023-09-25 17:19 UTC, merged