Arbitrary Bridge pool fee token types
anoma/namada pull request #1795
Opened 2023-08-08 15:36 UTC by sug0

## Describe your changes

Closes #1704
Doesn't solve #1799 nor #1800

The PR is configured to merge into the base ([tiago/update-ethbridge-rs](https://github.com/anoma/namada/tree/tiago/update-ethbridge-rs)) to make reviewing easier. It should be changed back to `main`, once the base is upstreamed.

## Indicate on which release or other PRs this topic is based on

Based on #1789

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

2023-08-09 16:21 UTC, sug0 commented
might still add one or two tests to check that the appropriate keys are changed when the fee token is different from NAM, while handling ethereum events

2023-08-11 08:46 UTC, batconjurer commented on shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
> +use std::borrow::Cow;
You've really been on a Cow kick lately.

2023-08-11 08:50 UTC, batconjurer commented on shared/src/ledger/native_vp/ethereum_bridge/bridge_pool_vp.rs
> +    /// Check that the gas was correctly escrow.
```suggestion
    /// Check that the gas was correctly escrowed.
```

2023-08-11 09:20 UTC, batconjurer requested changes

2023-08-11 09:20 UTC, batconjurer commented on apps/src/lib/cli.rs
> +    pub const BRIDGE_POOL_GAS_AMOUNT: ArgDefault<token::DenominatedAmount> =
This amount will need to be validated. When reading from string, it gives it the minimum denom possible to fit the amount. We need to look up the denom from storage and increase it if necessary. If too much precision was given, we must fail.

2023-08-16 14:08 UTC, tzemanovic approved these changes

2023-08-31 08:33 UTC, batconjurer approved these changes

2023-09-06 21:03 UTC, merged