Add IBC E2E test with Hermes
anoma/namada pull request #1797
Opened 2023-08-09 11:11 UTC by yito88

## Describe your changes
Add a new IBC E2E test with Hermes relaying

## Indicate on which release or other PRs this topic is based on
#1784

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2023-12-11 14:32 UTC, sug0 approved these changes

2023-12-11 14:32 UTC, sug0 commented on tests/src/e2e/setup.rs
> +) -> Result<NamadaCmd>
hm this is kinda hacky. oh well :D

2023-12-12 13:10 UTC, tzemanovic commented
the e2e test failed on 1st attempt, retrying

2023-12-12 13:31 UTC, sug0 requested changes
ah you're right, oops. looks like it failed again.

2023-12-12 20:35 UTC, yito88 commented
ah, it should fail because Hermes for Namada 0.28.0 ([1.7.1-namada-beta5](https://github.com/heliaxdev/hermes/releases/tag/v1.7.1-namada-beta5)) is required.
For CI, #2237 is required to build Hermes with the target Namada.

2023-12-12 22:15 UTC, sug0 commented
I see

2023-12-12 22:16 UTC, sug0 approved these changes

2024-01-03 10:39 UTC, yito88 commented
Rebased. The E2E test passed with Hermes `1.7.4-namada-beta6`.

2024-01-13 19:01 UTC, merged