Tiago/fix bp recommendations
anoma/namada pull request #1811
Opened 2023-08-13 10:56 UTC by sug0

## Describe your changes

Closes #1799

## Indicate on which release or other PRs this topic is based on

Based on #1795

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2023-08-15 08:30 UTC, batconjurer requested changes
The code changes look fine, but needs to new unit tests to cover the new code paths for provided conversion tables.

2023-08-16 15:35 UTC, sug0 commented
@batconjurer  there's currently a gotcha in the recommendations algorithm, I think. the `transfer_to_ethereum_progress` RPC method skips "seen" Ethereum transfers. a transfer to be relayed is not recommended if it is not found in the array of transfers returned by `transfer_to_ethereum_progress`; in turn, all transfers considered for relaying are obtained from querying the current signed pool.

the current signed pool may be behind the most up to date Bridge pool, because of the vote extension tx lag. so, I believe the algorithm may recommend a transfer that has already been relayed, that still shows up in the signed pool.

a simple solution may be to return with an error if the signed Bridge pool nonce does not match the up to date Bridge pool nonce in storage. this way we never recommend transfers that have already been relayed and acted upon.

2023-08-17 14:20 UTC, batconjurer commented on core/src/std_ext.rs
> +    fn maybe_collect_result<C>(self) -> Result<C, E>
Is this used?

2023-08-17 14:57 UTC, sug0 commented
**TODO:** test recommending two different token types

2023-08-18 10:12 UTC, tzemanovic commented on core/src/std_ext.rs
I think you can already do this via https://doc.rust-lang.org/stable/std/result/enum.Result.html#impl-FromIterator%3CResult%3CA,+E%3E%3E-for-Result%3CV,+E%3E without `Default` and `Extend`. In bridge_pool.rs where it's used you can call `Result::from_iter` or assign the iter over result to `let iter_res: Result =`. But if you prefer the chained calls I don't mind keeping this, but I'd change it to:

```rust
pub trait MaybeCollectResult<T, E> {
    /// Collect all [`Ok`] values in the iterator, or fail.
    fn maybe_collect_result<C>(self) -> Result<C, E>
    where
        C: FromIterator<T>;
}

impl<I, T, E> MaybeCollectResult<T, E> for I
where
    I: Iterator<Item = Result<T, E>>,
{
    fn maybe_collect_result<C>(self) -> Result<C, E>
    where
        C: FromIterator<T>,
    {
        Result::from_iter(self)
    }
}
```

2023-08-18 10:15 UTC, tzemanovic approved these changes

2023-09-06 21:03 UTC, merged