Replay protection fix
anoma/namada pull request #1867
Opened 2023-09-06 13:31 UTC by grarco

## Describe your changes

## Indicate on which release or other PRs this topic is based on

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2023-09-28 06:35 UTC, murisi commented
> Since neither the Masp nor the ExtraData sections are mentioned in the header, adding, modifying or removing these sections wouldn't change the hash used for replay protection (but would still invalidate the commitments). So no malleability attack of these section can deceive the replay protection mechanism.

Hi @grarco , thanks for looking into the replay protection issues. If the Masp, ExtraData, or inner Signature section is tampered with, when would it be detected that the commitments have been invalidated? Before the gas fee is deducted from the wrapper signer or after? I am thinking back to the issue you brought up here: https://github.com/anoma/namada/issues/1567 .

2023-09-28 07:30 UTC, murisi commented
Also, given that the hardware wallet code is being frozen for auditing, is there a way to solve some of these issues without modifying the transaction format or the signing algorithm? Like, could we not somehow store the hash of the signature section over the wrapper, and the hash of the signature section over (data, code, MASP, extras) (as returned by `verify_signatures`) in replay storage? cc @adrianbrink

2023-09-28 11:06 UTC, grarco commented
> > Since neither the Masp nor the ExtraData sections are mentioned in the header, adding, modifying or removing these sections wouldn't change the hash used for replay protection (but would still invalidate the commitments). So no malleability attack of these section can deceive the replay protection mechanism.
> 
> Hi @grarco , thanks for looking into the replay protection issues. If the Masp, ExtraData, or inner Signature section is tampered with, when would it be detected that the commitments have been invalidated? Before the gas fee is deducted from the wrapper signer or after? I am thinking back to the issue you brought up here: #1567 .

So if the tampering happens directly on the encrypted sections, it's discovered while validating the wrapper transaction, so the tx is discarded and no fees are paid. This is because the wrapper signer still signs over all of the sections. If instead the tampering happens on the sections before they are encrypted, it gets discovered when we run the decrypted transaction, so after the fees have been paid. But this scenario can only happen if:

- The tampering has been performed by the wrapper signer themselves
- The tampering happened on the communication channel between the wrapper signer and the entity that produced the inner tx, still the wrapper signer is responsible for checking the validity of the received message

So fee payment looks correct to me in this case

2023-09-28 11:28 UTC, grarco commented
> Also, given that the hardware wallet code is being frozen for auditing, is there a way to solve some of these issues without modifying the transaction format or the signing algorithm? Like, could we not somehow store the hash of the signature section over the wrapper, and the hash of the signature section over (data, code, MASP, extras) (as returned by `verify_signatures`) in replay storage? cc @adrianbrink

I see, so this PR, if correct, I think proposes the least effort (in terms signatures effort) but it requires changing the `Signature` section format (and therefore the tx format) and also the signing algorithm. This is because the PR aims at closing #1683 too, it actually comes down to collapsing this and #1530 to the same problem, the lack of a signature on the `Header` coming from the inner tx signer.

The `Signature` struct has been changed in a single field, the `targets` field which has been turned from a `Vec` to a single `Hash`: in theory we can bring back the `Vec` without any problem (it will simply be a vector of one element).

For the signing algorithm we could do more or less the same, just revert it to the previous version's implementation (expecting an array of hashes) even though we'll provide only one hash

2023-10-16 07:41 UTC, Fraccaman commented
is this mergeable in 0.24.0?

2023-10-23 07:25 UTC, murisi submitted a review, later dismissed
Looks good to me, thanks!

2023-10-23 09:33 UTC, murisi requested changes
Looks good to me. There's just a minor issue with `CompressedSignature` expansion.

2023-10-23 09:33 UTC, murisi commented on .DS_Store
Is this file supposed to be here?

2023-10-23 09:33 UTC, murisi commented on core/src/proto/types.rs
`CompressedSignature` is the compressed form of a `Signature` returned by the hardware wallet. The software client expands it before sending it off to the protocol. Here, line 630 always expands the 0th index to the `header_hash()`. So how can we allow the hardware wallet to specify that a signature is over the `raw_header_hash()`? I'm thinking that we can use the sentinel index `255` to specify `tx.raw_header_hash()`. Like:
```
} else if idx == 255 {
    /// The 255th section is the raw header
    targets.push(tx.raw_header_hash());
} else {
```

2023-10-23 09:45 UTC, grarco commented on core/src/proto/types.rs
Nice catch! Yes I think this solution works fine

2023-10-24 11:26 UTC, merged