Add new types related with subsequent vote extensions PRs
anoma/namada pull request #192
Opened 2022-07-15 13:45 UTC by sug0

This PR will add new types to be used by the ethereum bridge integration branch.

The current spec was derived from a meeting me, James and Jacob had, so it's still not finalized, but the current version can be found [here](https://hackmd.io/RTtsCl_RRBu2acISHL0-2g).

2022-07-15 14:31 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +    pub fn decompress<D, H>(self, storage: &Storage<D, H>) -> Vec<Signed<VoteExtension>>
instead of passing in the storage here, lets just pass in the block height.

2022-07-15 14:32 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +    }
I would love a unit test or two for the decompress algorithm if that's not too much trouble.

2022-07-18 15:17 UTC, james-chf approved these changes
lgtm. During [VerifyVoteExtension](https://docs.tendermint.com/master/spec/abci++/abci++_methods.html#verifyvoteextension) we get access to the voting validator's Tendermint address, I'm thinking ultimately we will want to check that matches up with the application-level signature of the vote extension being verified, to prevent replays of stale vote extensions from a previous failed round for the the current round which is at the same block height.

2022-07-19 11:22 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +pub struct VoteExtension {
This is fine for now, but I will move this struct to a different place later since vote extesnions have uses other than just the ethereum bridge.

2022-07-19 11:28 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +pub struct VoteExtension {
But I will have to think about how to decompress digests in that case, so I'm not going to spend brain power on it now.

2022-07-19 11:38 UTC, batconjurer requested changes
Two small requests. Otherwise looks good.

2022-07-19 11:38 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +            if !nulls.contains(&addr) {
You're completely right. We should remove the nulls field. I would rather have slightly longer execution times if it means a smaller digest.

2022-07-19 11:38 UTC, batconjurer commented on shared/src/types/ethereum_events/vote_extensions.rs
> +        assert_eq!(ext, decompressed);
For complete sanity's sake, can we test that that signatures for each `Signed<VoteExtension>` from the decompressed verifies correctly?
```
assert!(decompressed[0].verify(&sk_1.ref_to()).is_ok());
assert!(decompressed[1].verify(&sk_2.ref_to()).is_ok());
```

2022-07-19 12:11 UTC, batconjurer approved these changes

2022-07-19 12:13 UTC, merged