Mock ledger services in integration tests
anoma/namada pull request #1976
Opened 2023-10-09 12:46 UTC by sug0

This enables processing Ethereum events, broadcasting protocol transactions, among other things, while running integration tests.

## Describe your changes

## Indicate on which release or other PRs this topic is based on

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2023-10-16 07:52 UTC, sug0 commented
Successful CI run with the services enabled: https://github.com/anoma/namada/pull/1976/commits/481fc7204dfb44ec5957a6bf7887beb2e6594350

2023-10-16 11:59 UTC, batconjurer requested changes
Code wise, one nit. Do we know this infra will work with ethereum tests though?

2023-10-16 12:02 UTC, sug0 commented
@batconjurer I think these changes encompass all the requirements to simulate an ethereum node running, as well as protocol txs generated from the observed ethereum events. if not... well, I can always refactor the code a bit in the PR that actually adds the eth bridge integration tests

2023-10-16 12:07 UTC, batconjurer approved these changes

2023-10-24 10:14 UTC, tzemanovic approved these changes

2023-10-24 11:26 UTC, merged