Refactor some helpers in queries.rs
anoma/namada pull request #241
Opened 2022-07-29 17:16 UTC by james-chf

Motivation is for some of this functionality to be available outside of the `Shell` (e.g. in `apply_tx` some of the current `queries.rs` functionality is duplicated in [this PR](https://github.com/anoma/namada/pull/210/files#diff-e02b60ae4f03bdbcdd62ba79596497e65f9f32ecad4d98a4f353cff428919f6e))

2022-08-01 08:06 UTC, batconjurer requested changes
It seems we can make all the query functions struct methods. Can we do that? `self.` is more readable than `fn(&self.storage,..` I think.

2022-08-01 08:21 UTC, sug0 commented
right, these could be struct methods of `Storage`

2022-08-01 08:56 UTC, james-chf commented
sure it makes sense for most if not all of these methods to be on an `impl` for `Storage`

2022-08-01 10:51 UTC, james-chf commented
done a bigger refactor to put most of the `queries.rs` methods that were on `Shell` onto a `QueriesExt` trait that is then implemented for `Storage`. These methods are higher level than the ones directly implemented on `Storage`. 

I've left on `Shell` the methods that seemed to be related to the ABCI /query method (i.e. were returning a Tendermint `response::Query`). Had to refactor also the `get_balance()` method to not use an ABCI-ish method that was left on `Shell`.

2022-08-02 08:59 UTC, sug0 commented on apps/src/lib/node/ledger/shell/queries.rs
> +}
Maybe move the documentation of each method you implemented in `Storage` here.

2022-08-02 09:00 UTC, sug0 commented on apps/src/lib/node/ledger/shell/queries.rs
> +}
Otherwise lgtm!

2022-08-02 10:38 UTC, sug0 approved these changes

2022-08-02 10:56 UTC, batconjurer approved these changes

2022-08-02 12:06 UTC, merged