Masp client invalidates spent notes
anoma/namada pull request #2534
Opened 2024-02-06 15:06 UTC by grarco

## Describe your changes

## Indicate on which release or other PRs this topic is based on

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2024-02-09 14:18 UTC, batconjurer commented on crates/sdk/src/masp.rs
> +/// Type alias for convenience and profit
:laughing:

2024-02-12 15:13 UTC, batconjurer requested changes

2024-02-13 13:35 UTC, grarco commented on crates/sdk/src/tx.rs
> +        }
I've moved this logic inside `check_balance_too_low_err`

2024-02-13 16:58 UTC, batconjurer approved these changes

2024-02-22 14:40 UTC, merged