cli: Propagating errors from fallible `CliToSdk` conversions
anoma/namada pull request #2832
Opened 2024-03-07 01:38 UTC by phasewalk1

## Describe your changes

This PR closes #1815. I've refactored the `CliToSdk` trait to propagate errors (such as I/O) from _fallible_ conversions between SDK and CLI types, this way we can avoid panics.

## Indicate on which release or other PRs this topic is based on
Based on `v0.31.8`

## Checklist before merging to `draft`
- [ ] I have added a changelog
- [ ] Git history is in acceptable state

2024-03-07 08:55 UTC, sug0 requested changes
hey. this is a great effort! thanks for submitting this patch!

I just have a couple of suggestions:

2024-03-07 08:55 UTC, sug0 commented on crates/apps/src/lib/cli.rs
> +                            .unwrap()
```suggestion
```

2024-03-07 08:55 UTC, sug0 commented on crates/apps/src/lib/cli.rs
>                      .collect(),
```suggestion
                    .collect()?,
```
you can collect a `Result<C, _>` for some collection `C` from an iterator yielding `Result` values

2024-03-07 08:55 UTC, sug0 commented on crates/apps/src/lib/cli.rs
> +            let _commission = std::fs::read(self.commission)?;
```suggestion
            let commission = std::fs::read(self.commission)?;
```
nit: why did you use an underscore for the identifier here?

2024-03-07 08:55 UTC, sug0 commented on crates/apps/src/lib/cli.rs
> +            let _proposal_data = std::fs::read(self.proposal_data)?;
```suggestion
            let proposal_data = std::fs::read(self.proposal_data)?;
```

2024-03-07 08:55 UTC, sug0 commented on crates/apps/src/lib/cli.rs
> +            });
```suggestion
            let proposal_data = self
                .proposal_data
                .map(std::fs::read)
                .transpose()?;
```

2024-03-07 09:07 UTC, phasewalk1 commented
> hey. this is a great effort! thanks for submitting this patch!
> 
> I just have a couple of suggestions:

hey thank you for the feedback. should I commit each suggested change individually?

2024-03-07 10:10 UTC, sug0 commented
I generally prefer `fixup!` commits then a rebase, but a single commit with all the review changes is fine too

2024-03-08 08:20 UTC, sug0 commented on crates/apps/src/lib/cli.rs
>                      .collect(),
```rs
.collect::<Result<Vec<_>, _>>
```

2024-03-09 01:39 UTC, phasewalk1 commented
I noticed that my fork is now quite behind the main branch (48 commits behind), and some CI tests are failing after I addressed your suggested changes. From my understanding, it's recommended to sync my fork with the main branch and rebase my changes on top of the latest commits.

However, I haven't had to do this process before (I'm an open source noob), and I'm a bit unsure about the proper steps. I want to ensure that I don't introduce any unintended changes or mess up the commit history. Could you please provide me with some guidance on how to proceed? Thank you 🙏 @sug0

2024-03-09 07:43 UTC, sug0 commented
hey @phasewalk1. yes, CI is probably broken on your current history, since we made changes in `main`. it should be pretty straight forward to do a rebase on `base`. run the following commands:
```
git remote add upstream https://github.com/anoma/namada
git fetch upstream
git rebase upstream/base
```
if you run into conflicts, I recommend installing Sublime Merge on macOS/Windows/Linux, or Meld on Windows/Linux to resolve them.

cheers,
-- sugo

2024-03-09 08:33 UTC, phasewalk1 commented
@sug0 cool, no conflicts. do i just force push to my remote now?

2024-03-09 09:06 UTC, sug0 commented
yup

2024-03-25 15:02 UTC, tzemanovic approved these changes

2024-03-25 17:16 UTC, phasewalk1 commented
hey @tzemanovic! I saw these changes got approved, should I rebase again and update my branch?

2024-03-28 14:47 UTC, tzemanovic commented
> hey @tzemanovic! I saw these changes got approved, should I rebase again and update my branch?

pls do just to get a CI run

2024-04-15 20:27 UTC, phasewalk1 commented
@brentstone I'm running into some merge conflicts that are giving me a bit of trouble. I'm a little pressed for time right now, as I have a couple math exams coming up that are taking priority. I'll have more time on Friday to fix this, but in the meantime, I can give you write access to my fork if you want to ship it sooner rather than later.

2024-04-23 17:23 UTC, phasewalk1 commented
Following up on this- the conflicts are a bit pesky; I want to make sure I'm accepting the right changes. Happy to collab on this or provide write access to the fork, but as it stands I could use a little guidance. Thanks for your patience.

2024-05-09 03:53 UTC, merged