Events voted on by validators are not voted on again
anoma/namada pull request #314
Opened 2022-08-10 15:01 UTC by batconjurer

Closes #308 

When a new ethereum event is seen, it is put in a queue to be included in a vote extension. Once that event is included on chain, it should be removed from the queue so that the validator that saw it stops including it in vote extensions.

2022-08-10 15:45 UTC, sug0 requested changes

2022-08-10 15:45 UTC, sug0 commented on apps/src/lib/node/ledger/shell/finalize_block.rs
> +    };
can you use `Vext` with its associated mod, for clarity? e.g. `ethereum_events::Vext`. same thing for `VextDigest`.

2022-08-10 15:54 UTC, james-chf approved these changes
I tested this patched on https://github.com/anoma/namada/pull/284 and it works

2022-08-11 10:01 UTC, sug0 approved these changes

2022-08-11 10:33 UTC, merged