crate refactors
anoma/namada pull request #3670
Opened 2024-08-19 15:49 UTC by tzemanovic

## Describe your changes 

closes #2111

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes

2024-08-26 08:33 UTC, Fraccaman commented
im not sure but do u mind checking if some of the paths in `codecov.yml` have changed?

2024-08-26 08:50 UTC, tzemanovic commented
> im not sure but do u mind checking if some of the paths in `codecov.yml` have changed?

not that I can see, why?

2024-08-27 10:14 UTC, sug0 requested changes

2024-08-27 10:14 UTC, sug0 commented on crates/node/src/protocol.rs
> +                                // via transactions
nit
```suggestion
                                // Replay protection entries should never be
                                // written to via transactions
```

2024-08-27 13:53 UTC, tzemanovic commented on crates/core/src/chain.rs
> +        self.serialize_to_vec().len()
I replaced it with a const fn in [c71daae](https://github.com/anoma/namada/pull/3670/commits/c71daae2ae1f343a81d1e91ccfaa1a826afa64b5)

2024-08-27 13:53 UTC, tzemanovic commented on crates/core/src/chain.rs
> +impl TryFrom<Vec<u8>> for BlockHash {
done in [c71daae](https://github.com/anoma/namada/pull/3670/commits/c71daae2ae1f343a81d1e91ccfaa1a826afa64b5) (it was already there so just rm'd this one)

2024-08-27 14:03 UTC, sug0 approved these changes

2024-08-27 16:51 UTC, merged