Behold the arse merkle tree
anoma/namada pull request #462
Opened 2022-09-09 11:25 UTC by batconjurer

Merging in the arse merkle tree

2022-09-12 12:23 UTC, sug0 requested changes

2022-09-12 12:23 UTC, sug0 commented on shared/src/ledger/storage/merkle_tree.rs
> +use itertools::Either;
maybe switch to [this `either`](https://docs.rs/either/latest/either/)? it has some nice methods, such as [`map_left`](https://docs.rs/either/latest/either/enum.Either.html#method.map_left)

2022-09-12 12:23 UTC, sug0 commented on shared/src/ledger/storage/merkle_tree.rs
> +use itertools::Either;
it is a relatively small dep, with optional `serde` encoding which can be disabled so build times are smaller

2022-09-12 12:23 UTC, sug0 commented on shared/src/ledger/storage/merkle_tree.rs
> +        };
`Either::map_left` and `Either::map_right`, then `Either::into_inner`, to get a `Result<bool>`

2022-09-12 12:23 UTC, sug0 commented on shared/src/ledger/storage/merkle_tree.rs
> +            }
same thing here, with the maps?

2022-09-20 09:45 UTC, sug0 approved these changes

2022-09-26 12:13 UTC, james-chf approved these changes

2022-09-29 07:59 UTC, batconjurer commented
pls update wasm

2022-09-29 08:17 UTC, merged