Ensure Ethereum events endpoint shuts down correctly
anoma/namada pull request #542
Opened 2022-10-04 14:55 UTC by james-chf

This is a quick PR to improve the fake Ethereum events endpoint
- refactor and add some docstrings
- make it so that it shuts down correctly (fixes https://github.com/anoma/namada/issues/507)
- listen on `0.0.0.0:3030` rather than `127.0.0.1:3030` so that the endpoint can be more easily exposed from within Docker containers (as are being used in [anoma/ethereum-bridge-e2e-tests](https://github.com/anoma/ethereum-bridge-e2e-tests))

2022-10-04 14:56 UTC, james-chf commented on apps/src/lib/node/ledger/ethereum_node/test_tools/events_endpoint.rs
> +            poll_fn(|cx| abort_sender.poll_closed(cx)).await;
We now shut down in a similar way to how the mock oracle does. That is, we await the `abort_sender` channel that was passed to us to be closed.

2022-10-04 15:26 UTC, sug0 requested changes

2022-10-06 08:32 UTC, batconjurer approved these changes
Looks good. Will need some changes to handled the bounded channels.

2022-10-06 10:40 UTC, james-chf commented
I've made sure the bounded sender changes aren't lost due to the move of that module to new file `events_endpoint.rs`, have restacked and force pushed again since the unit tests CI job seemed stuck, but maybe GitHub actions is having issues?

2022-10-06 12:33 UTC, merged