Fix the abcipp feature flag
anoma/namada pull request #871
Opened 2022-12-08 10:25 UTC by batconjurer

This PR fixes up the `abcipp` feature flag. It should not compile, pass clippy, and tests. Quite a few places where there were flags before have been removed to keep the code it guarded under active maintenance. The shims were reworked to get rid to the tx records. Validating val set updates has been refactored to be switched off for the moment.

2022-12-08 13:48 UTC, james-chf approved these changes

2022-12-08 13:48 UTC, james-chf commented on apps/src/lib/node/ledger/shims/abcipp_shim_types.rs
> +                Self::default()
should there be a `TODO`/`unimplemented!` here? We have https://github.com/anoma/namada/issues/198 as a catch all issue we can link to

2022-12-09 08:46 UTC, sug0 requested changes

2022-12-09 08:46 UTC, sug0 commented on apps/src/lib/node/ledger/shell/vote_extensions.rs
> -            })
can you leave the original `NOTE` comment in?

2022-12-09 08:46 UTC, sug0 commented on shared/src/ledger/queries_ext.rs
> +        false
:joy:

2022-12-09 11:23 UTC, merged