Plug `BlockSpaceAllocator` logic into `ProcessProposal`
anoma/namada pull request #895
Opened 2022-12-14 16:27 UTC by sug0

Based on #897

Adds some validation of the `BlockSpaceAllocator` logic into `ProcessProposal`.

**SPECS:** <https://hackmd.io/unZg8ia4SZCKDQIY-s8d_Q?view=>

2022-12-16 13:13 UTC, james-chf approved these changes

2022-12-16 13:51 UTC, sug0 commented on apps/src/lib/node/ledger/shell/prepare_proposal.rs
> +                let _ = alloc;
I can refactor this to make the remaining txs allocator do nothing, to avoid this noise here

2022-12-16 14:09 UTC, sug0 commented on apps/src/lib/node/ledger/shell/mod.rs
> +                          * [`ErrorCodes::is_recoverable`] */
that's how it was defined in `ProcessProposal` before, this `is_recoverable()` method came from a `ProcessProposal` refactor back when I was working on eth events vote extensions

2022-12-19 10:03 UTC, batconjurer requested changes
nit: Can the tx building fns in prepare proposal be defined in the same order they are used in the main method?

2022-12-20 09:35 UTC, sug0 commented on apps/src/lib/node/ledger/shell/process_proposal.rs
> +        metadata: &mut ValidationMeta,
oh yeah, we need to add a new error code there

2022-12-20 12:52 UTC, batconjurer approved these changes

2022-12-20 15:53 UTC, merged