Write specs for the `BlockSpaceAllocator`
anoma/namada pull request #907
Opened 2022-12-16 15:16 UTC by sug0

Based on #895

The relevant files to review are under `documentation/`

2022-12-19 09:08 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +parameter) have a minimum value of $1\ B$, and a hard cap of $100\
such a nit, but maybe easier to read if you use `byte` instead of `B`.

2022-12-19 10:14 UTC, batconjurer requested changes
Love the diagrams

2022-12-19 10:14 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +value is static throughout the course of the chain) and set Tendermint blocks'
I think it should be  changeable by governance.

2022-12-19 10:14 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +combined bytes $P_{Len} : P_{Len} \le MaxProposalBytes$.
```suggestion
combined bytes $P_{Len} \le MaxProposalBytes$.
```

2022-12-19 10:14 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +to the short-circuit behavior of a `TxBin`, on allocation errors, some space
we should probably state the reasoning behind filling up unused space with protocol txs only.

2022-12-19 10:14 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +validator $v : v \in V$ checks:
```suggestion
validator $v \in V$ checks:
```

2022-12-19 10:14 UTC, batconjurer commented on documentation/specs/src/base-ledger/block-space-allocator.md
> +* If the length of $P$ in bytes, defined as $P_{Len} : P_{Len} = \sum_{tx \in
```suggestion
* If the length of $P$ in bytes, defined as $P_{Len} := \sum_{tx \in 
```

2022-12-21 15:24 UTC, batconjurer approved these changes

2022-12-21 15:24 UTC, cwgoes approved these changes

2022-12-21 15:42 UTC, merged