Create an Ethereum bridge sub-crate
anoma/namada pull request #923
Opened 2022-12-19 10:39 UTC by batconjurer

This PR refactors much of Ethereum bridge out of the `shared` crate and into its own crate. The only things remaining in the shared crate are the implementations of the native VPs.

The `QueriesExt` trait has been moved to `proof_of_stake` and been renamed to `PosQueries`.

 I was unable to lift any logic from `core` into the new subcrate as it either related to storage or txs, both of which are appropriate in `core`.

2022-12-19 15:55 UTC, sug0 requested changes
hm it's not as bad as I thought it'd be, but it'll probably still be annoying to rebase against haha

2022-12-20 09:36 UTC, batconjurer commented on ethereum_bridge/src/lib.rs
> +};
nope, that was bad copy pasta from shared.

2022-12-20 10:02 UTC, sug0 approved these changes

2022-12-20 13:06 UTC, tzemanovic approved these changes
LGTM!

2022-12-20 13:23 UTC, merged